# Generated by Django 3.2.5 on 2022-07-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('travelPics', models.ImageField(blank=True, upload_to='travelPics')),
                ('destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='globe_app.destination')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('budgetStart', models.FloatField()),
                ('budgetEnd', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globe_app.destination')),
                ('travelNotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globe_app.travelnote')),
            ],
        ),
        migrations.CreateModel(
            name='TravelWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globe_app.destination')),
                ('travelNotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globe_app.travelnote')),
            ],
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelPics', models.ImageField(blank=True, upload_to='travelPics')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globe_app.destination')),
                ('travelNotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globe_app.travelnote')),
            ],
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globe_app.forumpost')),
            ],
        ),
    ]
