# Generated by Django 3.2.5 on 2022-08-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelhistory',
            options={'verbose_name_plural': 'Travel Histories'},
        ),
        migrations.RemoveField(
            model_name='travelnote',
            name='travelPics',
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='owner',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='travelwishlist',
            name='owner',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='upcomingtravel',
            name='dateFlexibility',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='destination',
            name='locationName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='travelNotes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='upcomingtravel',
            name='owner',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('messageRead', models.BooleanField(default=False)),
                ('messageReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('messageSender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('messageThread', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='globe_app.messagethread')),
            ],
        ),
    ]
