# Generated by Django 3.2.5 on 2022-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingtravel',
            name='owner',
            field=models.CharField(default='testing3', max_length=128),
        ),
    ]
