# Generated by Django 3.2.5 on 2022-07-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non Binary'), ('PNTD', 'Prefer not to say')], max_length=4),
        ),
    ]
