# Generated by Django 3.2.5 on 2022-07-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtravel',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='globe_app.userprofile'),
        ),
    ]
