# Generated by Django 3.2.5 on 2022-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtravel',
            name='dateFlexibility',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='destination',
            name='locationName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='upcomingtravel',
            name='owner',
            field=models.CharField(max_length=128),
        ),
    ]
