# Generated by Django 3.2.5 on 2022-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0002_auto_20220809_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelwishlist',
            name='owner',
            field=models.CharField(max_length=128),
        ),
    ]
