# Generated by Django 3.2.5 on 2022-07-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0002_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingtravel',
            name='travelNotes',
        ),
        migrations.AlterField(
            model_name='upcomingtravel',
            name='budgetEnd',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='upcomingtravel',
            name='budgetStart',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
