# Generated by Django 3.2.5 on 2022-08-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0003_message_messagethread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='messageReceiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='messageSender',
        ),
        migrations.RenameField(
            model_name='messagethread',
            old_name='sender',
            new_name='user',
        ),
    ]
