# Generated by Django 3.2.5 on 2022-08-11 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0004_alter_travelwishlist_travelnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtravel',
            name='travelNotes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postreply',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='TravelNote',
        ),
    ]
