# Generated by Django 3.2.5 on 2022-08-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
