# Generated by Django 3.2.5 on 2022-08-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0005_auto_20220811_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingtravel',
            options={'ordering': ['destination']},
        ),
    ]
