# Generated by Django 3.2.5 on 2022-08-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0006_alter_upcomingtravel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingtravel',
            options={},
        ),
    ]
