# Generated by Django 3.2.5 on 2022-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0006_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelhistory',
            name='owner',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
