# Generated by Django 3.2.5 on 2022-08-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0007_auto_20220808_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelhistory',
            name='owner',
            field=models.CharField(max_length=128),
        ),
    ]
