# Generated by Django 3.2.5 on 2022-08-31 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0007_alter_upcomingtravel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreply',
            name='post',
        ),
        migrations.RemoveField(
            model_name='travelhistory',
            name='travelPics',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='PostReply',
        ),
    ]
