# Generated by Django 3.2.5 on 2022-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe_app', '0008_alter_travelhistory_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelhistory',
            options={'verbose_name_plural': 'Travel Histories'},
        ),
        migrations.RemoveField(
            model_name='travelnote',
            name='travelPics',
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='travelNotes',
            field=models.TextField(blank=True),
        ),
    ]
