# Generated by Django 3.2.5 on 2022-08-03 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='postreply',
            name='date',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postreply',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
