# Generated by Django 3.2.5 on 2022-08-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_auto_20220803_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreply',
            options={'verbose_name_plural': 'post replies'},
        ),
    ]
